version: '3'
services:
  storage:
    image: busybox
    volumes:
      - storage:/var/lib/mysql

  mysql:
    image: mysql:5.7
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  scala:
    image: "h3poteto/scala"
    volumes:
      - .:/var/opt/app
    links:
      - mysql:mysql
    command: /bin/bash

volumes:
  storage:
