version: '3'
services:
  storage:
    image: busybox
    volumes:
      - storage:/var/lib/mysql

  mysql:
    image: mysql:5.7
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  scala:
    image: h3poteto/play
    env_file: .docker-env
    environment:
      PLAY_ENV: "development"
    volumes:
      - .:/var/opt/app
      - .ivy2:/home/scala/.ivy2
      - .activator:/home/scala/.activator
      - .sbt:/home/scala/.sbt
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - node:node
    command: /bin/bash
  node:
    image: node:7.8.0-alpine
    user: node
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    entrypoint: sh -c
    command: |
      "npm install && \
      npm run watch"

volumes:
  storage:
