version: '3'
services:
  scala:
    image: h3poteto/ayanerer
    environment:
      DB_URL: $DB_URL
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SECRET: $SECRET
    ports:
      - "9000:9000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 10s
  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - scala
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_ADDR: scala
      SERVER_PORT: 9000
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx/:/var/log/nginx/
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
